# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef84c8a6de96662f22af0b14adfd15ef752b4be5c81dcf7a1b4f7eb804fde103a6d32ad0c3d3d99bc3c68e65afea67a9a76b73f50d826623d27d233e9e3b341

test:
  secret_key_base: df6edbbc18d54f1915d182e15840b38766f5ef8851dbffa4ba3c70743f32470f7ccaa236616cf8220e6091bee429f5b9deb6837e83860816980c49af10b33feb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: aef84c8a6de96662f22af0b14adfd15ef752b4be5c81dcf7a1b4f7eb804fde103a6d32ad0c3d3d99bc3c68e65afea67a9a76b73f50d826623d27d233e9e3b341
